
language: cpp

dist: bionic

compiler: gcc

os:
  -linux

script: 
  - g++ terminal/src/test.cpp
    src/terminal.cpp
    src/cli/commands.cpp
    src/cli/commands/command.cpp
    src/cli/commands/wc_cmd.cpp
    src/cli/commands/cat_cmd.cpp
    src/cli/commands/exit_cmd.cpp
    src/cli/commands/pwd_cmd.cpp
    src/cli/commands/echo_cmd.cpp
    -lstdc++fs -o
    terminal_test
  - ./terminal_test
